<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3265" started-at="2021-03-05T16:38:48Z" finished-at="2021-03-05T16:38:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3265" started-at="2021-03-05T16:38:48Z" finished-at="2021-03-05T16:38:51Z">
      <class name="testCases.GET_Or_Read_A_Product">
        <test-method status="FAIL" signature="read_A_Product()[pri:0, instance:testCases.GET_Or_Read_A_Product@3ee0fea4]" name="read_A_Product" duration-ms="3210" started-at="2021-03-05T16:38:48Z" finished-at="2021-03-05T16:38:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Product id Missmatch expected [1204] but found [1203],
ProductName Missmatch!!! expected [Samsung S20] but found [i phone 12 pro],
productDescription Missmatch!!! expected [Pretty amazing phone] but found [Kind of OK]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Product id Missmatch expected [1204] but found [1203],
ProductName Missmatch!!! expected [Samsung S20] but found [i phone 12 pro],
productDescription Missmatch!!! expected [Pretty amazing phone] but found [Kind of OK]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testCases.GET_Or_Read_A_Product.read_A_Product(GET_Or_Read_A_Product.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read_A_Product -->
      </class> <!-- testCases.GET_Or_Read_A_Product -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
