<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-NFATJD6" name="testCases.PUT_Or_Update_A_Product" tests="1" failures="1" timestamp="28 Feb 2021 18:09:20 GMT" time="4.521" errors="0">
  <testcase name="update_A_Product" time="4.521" classname="testCases.PUT_Or_Update_A_Product">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ProductName Missmatch!!! expected [Samsung S20] but found [Samsung S21]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ProductName Missmatch!!! expected [Samsung S20] but found [Samsung S21]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testCases.GET_Or_Read_A_Product.read_A_Product(GET_Or_Read_A_Product.java:50)
at testCases.PUT_Or_Update_A_Product.update_A_Product(PUT_Or_Update_A_Product.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- update_A_Product -->
</testsuite> <!-- testCases.PUT_Or_Update_A_Product -->
